name: CI/CD Pipeline

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run black (code style)
        run: black --check .

      - name: Run flake8 (linter)
        run: flake8 .

      - name: Run mypy (type check)
        run: mypy .

      - name: Run pytest (unit/integration tests)
        run: pytest tests/
